name: Build Images

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 3 * * *' # run at 3 AM UTC

# This stops any running jobs when a new commit is pushed
# Reference: https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  version_info:
    name: Generate Version Info
    runs-on: ubuntu-latest
    outputs:
      software_version: ${{ steps.version_info.outputs.software_version }}
    steps:
      # We will use the date and month as the tag for the image in the format YYYY-MM.
      # This will allow us to store older images and easily identify when they were built.
      # I don't need finer granularity than this for my use case. This will be set in the
      # version_info job and used in the build_image jobs
      - id: version_info
        run: echo "software_version=$(date +%Y-%m)" >> $GITHUB_OUTPUT

  build_image:
    name: Build and Publish Images
    needs: version_info
    strategy:
      fail-fast: false
      matrix:
        include:
          - build-image: ubuntu:latest
            image-name: dotfiles/base
          - build-image: ghcr.io/dlrobson/latex-dev-container:latest
            image-name: dotfiles/latex
    uses: ./.github/workflows/build_image_reusable.yml
    with:
      base-image: ${{ matrix.build-image }}
      image-name: ${{ matrix.image-name }}
      software-version: ${{ needs.version_info.outputs.software_version }}
      require-base-image-changed: ${{ github.event_name == 'schedule' }}
