name: Publish Docker image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dlrobson
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            USER_ID=$(id -u)
            GROUP_ID=$(id -g)
          push: ${{ github.event_name != 'pull_request' }}
          tags: dlrobson/dotfiles:latest
          platforms: linux/amd64,linux/arm64