name: Build Images

on:
  push:
    branches:
      - master
  pull_request:

# This stops any running jobs when a new commit is pushed
# Reference: https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_image:
    name: Build and Publish Images
    strategy:
      fail-fast: false
      matrix:
        include:
          - build-image: ubuntu:latest
            image-name: ghcr.io/dlrobson/dotfiles/base
          - build-image: rust:slim
            image-name: ghcr.io/dlrobson/dotfiles/rust
    uses: ./.github/workflows/build_image_reusable.yml
    with:
      base-image: ${{ matrix.build-image }}
      image-name: ${{ matrix.image-name }}
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
