name: Reusable Build and Publish Image Workflow

on:
  workflow_call:
    inputs:
      base-image:
        required: true
        type: string
      image-name:
        required: true
        type: string
      software-version:
        required: true
        type: string
      require-base-image-changed:
        required: false
        type: boolean
        default: false

jobs:
  build_image:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Pull base image
        run: docker pull ${{ inputs.base-image }}

      - id: base_image_digest
        run: echo "base_image_digest=$(docker image inspect --format='{{index .RepoDigests 0}}' ${{ inputs.base-image }})" >> $GITHUB_OUTPUT

      - name: Check if base image has changed
        id: base_image_changed
        run: |
          if [ "${{ inputs.require-base-image-changed }}" = "false" ]; then \
            echo "base_image_changed=true" >> $GITHUB_OUTPUT; \
          else \
            docker pull ghcr.io/dlrobson/${{ inputs.image-name }}:latest || :; \

            base_image_digest=$(docker inspect --format='{{index .Config.Labels "org.opencontainers.image.base.digest"}}' ghcr.io/dlrobson/${{ inputs.image-name }}:latest) || :; \

            echo "base_image_digest=$base_image_digest"; \
            echo "current_base_image_digest=${{ steps.base_image_digest.outputs.base_image_digest }}"; \
            
            if [ "${{ steps.base_image_digest.outputs.base_image_digest }}" != "$base_image_digest" ]; then \
              echo "Base image has changed"; \
              echo "base_image_changed=true" >> $GITHUB_OUTPUT; \
            else \
              echo "Base image has not changed"; \
              echo "base_image_changed=false" >> $GITHUB_OUTPUT; \
            fi \
          fi
      - name: Check out the repo
        if: ${{ steps.base_image_changed.outputs.base_image_changed != 'false' }}
        uses: actions/checkout@v4

      - name: Docker metadata
        if: ${{ steps.base_image_changed.outputs.base_image_changed != 'false' }}
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/dlrobson/${{ inputs.image-name }}
          tags: |
            latest
            ${{ inputs.software-version }}
          labels: |
            org.opencontainers.image.version=${{ inputs.software-version }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.base.digest=${{ steps.base_image_digest.outputs.base_image_digest }}
          annotations: |
            org.opencontainers.image.version=${{ inputs.software-version }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.base.digest=${{ steps.base_image_digest.outputs.base_image_digest }}

      - name: Set up QEMU
        if: ${{ steps.base_image_changed.outputs.base_image_changed != 'false' }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ steps.base_image_changed.outputs.base_image_changed != 'false' }}
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        if: ${{ steps.base_image_changed.outputs.base_image_changed != 'false' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        if: ${{ steps.base_image_changed.outputs.base_image_changed != 'false' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            UID=1000
            GID=1000
            BASE_IMAGE=${{ inputs.base-image }}
          push: ${{ github.event_name != 'pull_request' }}
          annotations: |
            ${{ steps.metadata.outputs.annotations }}
          tags: |
            ${{ steps.metadata.outputs.tags }}
          labels: |
            ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      # When tags are overwritten, the old tags are not removed from the registry.
      # This action removes the old tags. This also handles multi-arch manifests, and
      # does not delete untagged images linked to the manifest.
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: ${{ inputs.image-name }}
          token: ${{ secrets.GITHUB_TOKEN }}

